services:
  database:
    image: postgres:16.1-alpine3.19
    restart: "no"
    healthcheck:
      test: "/etc/init.d/postgresql status"
      timeout: 1s
      retries: 60
    volumes:
      - "./docker/db/postgresql:/var/lib/postgresql/data"
    ports:
      - "5532:${DATABASE_PORT}"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"

  php:
    build:
      context: ./docker/php
    tty: true
    restart: "no"
    volumes:
      - ".:/var/www/html"
      - "~/.composer:/home/docker/.composer"
      - "~/.ssh:/home/docker/.ssh"
    depends_on:
      - database

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ".:/var/www/html"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - database

  mailer:
    image: schickling/mailcatcher
    ports:
    - "1125:1025"
    - "1180:1080"
